include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-raw-types: true
  exclude:
    - analyser_options.yaml
    - "**/*.g.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    - camel_case_types
    - empty_constructor_bodies
